# Generated by Django 4.2.7 on 2025-01-25 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_userprofile_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("gerente", "Gerente"),
                    ("analista", "Analista"),
                    ("suporte", "Suporte"),
                    ("cliente", "Cliente"),
                    ("usuario", "Usuario"),
                ],
                default="usuario",
                max_length=20,
            ),
        ),
    ]
