# Generated by Django 4.2.7 on 2025-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_userprofile_approval_date_userprofile_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone"
            ),
        ),
    ]
